version: "3.8" # Use a supported version in line with Docker Engine capabilities

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1 # Ensures that Python output is logged instantly
